// Product Action Types
export const ProductActionTypes = {
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_PRODUCTS_BY_CATEGORY: "FETCH_PRODUCTS_BY_CATEGORY",
  FETCH_PRODUCT_DETAILS: "FETCH_PRODUCT_DETAILS",
  SORT_PRODUCTS: "SORT_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",

  REQUEST_LOADING: "REQUEST_LOADING",
  REQUEST_FAILURE: "REQUEST_FAILURE",
  REQUEST_FILTERING_STARTED: "REQUEST_FILTERING_STARTED",
};
